#!/usr/bin/env python3
"""Generate cram/ from the chapters. Re-run after any chapter edit."""
import re, glob, os

CHAPTERS = sorted(glob.glob('notes/week-*/*.md'))

def section(txt, name):
    """Return the body of H2 `name`, or '' ."""
    m = re.search(rf'^## {re.escape(name)}\s*$(.*?)(?=^## |\Z)', txt, re.M | re.S)
    return m.group(1).strip() if m else ''

def subsection(txt, name):
    m = re.search(rf'^### {re.escape(name)}\s*$(.*?)(?=^### |^## |\Z)', txt, re.M | re.S)
    return m.group(1).strip() if m else ''

def title_of(txt, path):
    m = re.search(r'^# (.+)$', txt, re.M)
    return m.group(1) if m else os.path.basename(path)

def rel(path):
    return '../' + path

def reroot(body, chapter_path):
    """Rewrite links inside an extracted section so they resolve from cram/."""
    d = os.path.dirname(chapter_path)                      # e.g. notes/week-03
    def fix(m):
        label, tgt = m.group(1), m.group(2)
        if tgt.startswith(('http', '#')):
            return m.group(0)
        resolved = os.path.normpath(os.path.join(d, tgt))  # repo-relative
        return f'[{label}](../{resolved})'
    return re.sub(r'\[([^\]]*)\]\((?!#)([^)]+\.(?:md|png|jpg|jpeg)[^)]*)\)', fix, body)

chapters = []
for p in CHAPTERS:
    if not os.path.isfile(p): continue
    t = open(p, encoding='utf8').read()
    chapters.append((p, title_of(t, p), t))

# ---------------------------------------------------------------- formula sheet
out = ["# Formula Sheet",
       "",
       "Every **Must-memorise** entry from all chapters, in course order. Generated from the "
       "chapters by `_build/build_cram.py` — edit the chapters, not this file.",
       ""]
for p, title, t in chapters:
    body = reroot(subsection(section(t, 'Exam pack'), 'Must-memorise'), p)
    if not body: continue
    out += [f"## [{title}]({rel(p)})", "", body, ""]
open('cram/formula-sheet.md', 'w', encoding='utf8').write('\n'.join(out))

# ------------------------------------------------------------------ exam traps
out = ["# Every MCQ Trap in the Course",
       "",
       "Collected from all chapters' **Likely MCQ traps**. Read this the night before. Generated by "
       "`_build/build_cram.py`.",
       ""]
n_traps = 0
for p, title, t in chapters:
    body = reroot(subsection(section(t, 'Exam pack'), 'Likely MCQ traps'), p)
    if not body: continue
    n_traps += len(re.findall(r'^\s*[-*] ', body, re.M))
    out += [f"## [{title}]({rel(p)})", "", body, ""]
out.insert(3, f"**{n_traps} traps** across {len(chapters)} chapters.\n")
open('cram/exam-traps.md', 'w', encoding='utf8').write('\n'.join(out))

# ----------------------------------------------------------- numbers to know
out = ["# Numbers Worth Knowing",
       "",
       "Every figure an MCQ can key on — parameter counts, error rates, years, kernel sizes, "
       "defaults. Generated by `_build/build_cram.py`.",
       ""]
for p, title, t in chapters:
    body = reroot(subsection(section(t, 'Exam pack'), 'Numbers worth knowing'), p)
    if not body: continue
    out += [f"## [{title}]({rel(p)})", "", body, ""]
open('cram/numbers.md', 'w', encoding='utf8').write('\n'.join(out))

# --------------------------------------------------------------- week summaries
out = ["# Week Summaries",
       "",
       "The one-paragraph version of every lecture — its **Why this lecture exists** section. "
       "Use this to rebuild the thread of the course quickly, or to decide what to re-read.",
       ""]
cur_week = None
for p, title, t in chapters:
    m = re.search(r'week-(\d+)', p)
    wk = m.group(1) if m else None
    if wk != cur_week:
        cur_week = wk
        out += [f"## Week {int(wk)}" if wk else "## Supplementary", ""]
    why = reroot(section(t, 'Why this lecture exists') or section(t, 'Why this chapter exists'), p)
    out += [f"### [{title}]({rel(p)})", "", why, ""]
open('cram/week-summaries.md', 'w', encoding='utf8').write('\n'.join(out))

# --------------------------------------------------------------- self-test bank
out = ["# Self-Test Bank",
       "",
       "Every self-test question in the course, answers hidden behind the collapsed blocks. "
       "Work on paper before expanding. Generated by `_build/build_cram.py`.",
       ""]
n_q = 0
for p, title, t in chapters:
    body = reroot(subsection(section(t, 'Exam pack'), 'Self-test'), p)
    if not body: continue
    n_q += len(re.findall(r'^\d+\.', body, re.M))
    out += [f"## [{title}]({rel(p)})", "", body, ""]
out.insert(3, f"**{n_q} questions** across {len(chapters)} chapters.\n")
open('cram/self-test-bank.md', 'w', encoding='utf8').write('\n'.join(out))

print(f"built cram/ from {len(chapters)} chapters — {n_traps} traps, {n_q} self-test questions")
for f in sorted(glob.glob('cram/*.md')):
    print(f"  {f:<34}{os.path.getsize(f)/1024:7.1f} KB")
